"use client";

import { useEffect, useState } from "react";
import type { CSSProperties, FormEvent } from "react";
import { Chrome } from "./Chrome";

type AdminData = {
  analytics: { visits: number; users: number; revenue: number; content: number };
  users: { id: number; displayName: string; email: string; role: string; createdAt: string }[];
  comments: { id: number; contentId: string; displayName: string; body: string; createdAt: string }[];
  packages: { id: number; name: string; durationDays: number; price: number; discountPercent: number; active: number }[];
  vip: { bankName: string; accountNumber: string; accountHolder: string; headline: string; promotion: string; accentColor: string } | null;
};

const defaultVip = { bankName: "Хаан банк", accountNumber: "0000 0000 0000", accountHolder: "Зураас ХХК", headline: "VIP ертөнцөд нэгдээрэй", promotion: "Шинэ хэрэглэгчид 20% хямдрал", accentColor: "#8b6cf6" };

export function AdminDashboard() {
  const [tab, setTab] = useState("overview");
  const [data, setData] = useState<AdminData | null>(null);
  const [vip, setVip] = useState(defaultVip);
  const [saved, setSaved] = useState("");
  const load = () => fetch("/api/app/admin").then((r) => r.json()).then((value: AdminData) => { setData(value); if (value.vip) setVip(value.vip); }).catch(() => null);
  useEffect(load, []);
  const notify = (message: string) => { setSaved(message); setTimeout(() => setSaved(""), 2500); };
  const submitContent = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const body = Object.fromEntries(form); await fetch("/api/app/admin/content", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); event.currentTarget.reset(); notify("Бүтээл амжилттай нэмэгдлээ"); load(); };
  const saveVip = async () => { await fetch("/api/app/admin/vip", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(vip) }); notify("VIP тохиргоо хадгалагдлаа"); };
  const addPackage = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await fetch("/api/app/admin/package", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); event.currentTarget.reset(); notify("Шинэ багц нэмэгдлээ"); load(); };
  const nav = [{ id: "overview", icon: "⌁", label: "Analytics" }, { id: "content", icon: "▣", label: "Анимэ, манга" }, { id: "users", icon: "♙", label: "Хэрэглэгчид" }, { id: "comments", icon: "◌", label: "Сэтгэгдэл" }, { id: "membership", icon: "♔", label: "Membership" }];
  return <Chrome><main className="admin-page"><header className="admin-header"><div><small>УДИРДЛАГЫН САМБАР</small><h1>Dashboard</h1><p>Зураас сайтын контент, хэрэглэгч, орлого болон VIP тохиргоог удирдана.</p></div><a href="/">Сайт руу очих ↗</a></header><div className="admin-tabs">{nav.map((item) => <button className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)} key={item.id}><i>{item.icon}</i>{item.label}</button>)}</div>{saved && <div className="save-toast">✓ {saved}</div>}
    {tab === "overview" && <section className="dashboard-panel"><div className="metric-grid"><article><i>↗</i><small>НИЙТ ХАНДАЛТ</small><strong>{(data?.analytics.visits || 0).toLocaleString()}</strong><span>Сайтын үзэлт</span></article><article><i>♙</i><small>БҮРТГҮҮЛСЭН ХЭРЭГЛЭГЧ</small><strong>{data?.analytics.users || 0}</strong><span>Нийт бүртгэл</span></article><article><i>₮</i><small>НИЙТ ОРЛОГО</small><strong>{(data?.analytics.revenue || 0).toLocaleString()}₮</strong><span>VIP төлбөр</span></article><article><i>▣</i><small>НИЙТ КОНТЕНТ</small><strong>{data?.analytics.content || 20}</strong><span>Анимэ ба манга</span></article></div><div className="analytics-row"><article><div className="panel-title"><h2>Хандалтын тойм</h2><span>Сүүлийн 7 хоног</span></div><div className="fake-chart">{[42,60,48,78,67,92,81].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div><div className="chart-labels"><span>Да</span><span>Мя</span><span>Лх</span><span>Пү</span><span>Ба</span><span>Бя</span><span>Ня</span></div></article><article><div className="panel-title"><h2>Контентын бүтэц</h2></div><div className="donut"><strong>{data?.analytics.content || 20}</strong><small>бүтээл</small></div><p><i /> Анимэ <b>50%</b></p><p><i /> Манга <b>50%</b></p></article></div></section>}
    {tab === "content" && <section className="dashboard-panel two-column-admin"><form className="admin-form" onSubmit={submitContent}><div className="panel-title"><div><h2>Шинэ бүтээл нэмэх</h2><p>Каталогт анимэ эсвэл манга нэмнэ.</p></div></div><label>Slug / ID<input name="id" placeholder="solo-leveling" required /></label><label>Бүтээлийн нэр<input name="title" placeholder="Бүтээлийн нэр" required /></label><label>Эх нэр<input name="originalTitle" placeholder="Original title" /></label><div className="form-row"><label>Төрөл<select name="type"><option value="anime">Анимэ</option><option value="manhwa">Манхва</option><option value="manga">Манга</option></select></label><label>Он<input name="year" type="number" defaultValue={2026} /></label></div><div className="form-row"><label>Анги / бүлэг<input name="count" type="number" defaultValue={12} /></label><label>Үнэлгээ<input name="rating" type="number" step="0.1" defaultValue={8.5} /></label></div><label>Төрлүүд<input name="genres" placeholder="Action, Fantasy" /></label><label>Нүүр зураг URL<input name="image" type="url" placeholder="https://..." required /></label><button type="submit">＋ Бүтээл нэмэх</button></form><div className="admin-guide"><span>▣</span><h2>Контентын удирдлага</h2><p>Нэмсэн бүтээл нүүр хуудасны тохирох Анимэ эсвэл Манга хэсэгт автоматаар гарна.</p><ul><li>Гарчгийг бүтнээр оруулна</li><li>2:3 харьцаатай нүүр зураг тохиромжтой</li><li>Төрлүүдийг таслалаар тусгаарлана</li></ul></div></section>}
    {tab === "users" && <section className="dashboard-panel"><div className="panel-title"><div><h2>Бүртгэлтэй хэрэглэгчид</h2><p>Нийт {data?.users.length || 0} хэрэглэгч</p></div><input placeholder="Хэрэглэгч хайх..." /></div><div className="admin-table"><div className="table-head"><span>Хэрэглэгч</span><span>Эрх</span><span>Бүртгүүлсэн</span></div>{data?.users.map((user) => <div key={user.id}><span className="user-cell"><i>{user.displayName.slice(0,2).toUpperCase()}</i><b>{user.displayName}<small>{user.email}</small></b></span><span><em>{user.role}</em></span><span>{user.createdAt}</span></div>)}</div></section>}
    {tab === "comments" && <section className="dashboard-panel"><div className="panel-title"><div><h2>Сэтгэгдлийн хяналт</h2><p>Анимэ болон манганы бүх сэтгэгдэл</p></div><span>{data?.comments.length || 0} сэтгэгдэл</span></div><div className="comment-admin-list">{data?.comments.length ? data.comments.map((comment) => <article key={comment.id}><span>{comment.displayName.slice(0,2).toUpperCase()}</span><div><b>{comment.displayName}<small> / {comment.contentId}</small></b><p>{comment.body}</p><time>{comment.createdAt}</time></div><button>•••</button></article>) : <div className="no-admin-data">Одоогоор сэтгэгдэл байхгүй байна.</div>}</div></section>}
    {tab === "membership" && <section className="dashboard-panel"><div className="membership-grid"><div><form className="admin-form vip-settings" onSubmit={(e) => { e.preventDefault(); saveVip(); }}><div className="panel-title"><div><h2>VIP хуудасны тохиргоо</h2><p>Банкны мэдээлэл ба сурталчилгааны текст</p></div></div>{([ ["headline","Гарчиг"], ["promotion","Хямдрал, урамшуулал"], ["bankName","Банкны нэр"], ["accountNumber","Дансны дугаар"], ["accountHolder","Данс эзэмшигч"] ] as const).map(([key,label]) => <label key={key}>{label}<input value={vip[key]} onChange={(e) => setVip({ ...vip, [key]: e.target.value })} /></label>)}<label>Үндсэн өнгө<input type="color" value={vip.accentColor} onChange={(e) => setVip({ ...vip, accentColor: e.target.value })} /></label><button type="submit">Тохиргоо хадгалах</button></form><form className="admin-form package-form" onSubmit={addPackage}><div className="panel-title"><h2>Төлбөрийн багц нэмэх</h2></div><div className="form-row"><label>Нэр<input name="name" placeholder="Сарын эрх" required /></label><label>Хугацаа<input name="durationDays" type="number" defaultValue={30} required /></label></div><div className="form-row"><label>Үнэ<input name="price" type="number" defaultValue={9900} required /></label><label>Хямдрал %<input name="discountPercent" type="number" defaultValue={0} /></label></div><button type="submit">＋ Багц нэмэх</button></form></div><aside className="live-preview"><div className="panel-title"><h2>Live preview</h2><span>LIVE</span></div><div className="preview-card" style={{ "--preview-accent": vip.accentColor } as CSSProperties}><small>♔ ZURAAS VIP</small><h2>{vip.headline}</h2><p>{vip.promotion}</p><div><span>{vip.bankName}</span><strong>{vip.accountNumber}</strong><b>{vip.accountHolder}</b></div><button>VIP эрх авах</button></div><h3>Идэвхтэй багцууд</h3>{data?.packages.map((p) => <div className="package-admin-row" key={p.id}><span><b>{p.name}</b><small>{p.durationDays} хоног</small></span><strong>{p.price.toLocaleString()}₮</strong><em>{p.discountPercent}%</em></div>)}</aside></div></section>}
  </main></Chrome>;
}
