"use client";

import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";

type AdminData = {
  analytics: { visits: number; users: number; revenue: number; bookmarks: number };
  periods: Record<string, { views: number; users: number; revenue: number; bookmarks: number }>;
  users: { id:number; displayName:string; email:string; role:string; usercode:string; vipUntil:string|null; createdAt:string }[];
  comments: { id:number; contentId:string; displayName:string; body:string; createdAt:string }[];
  packages: { id:number; name:string; durationDays:number; price:number; active:number }[];
  contents: { id:string; title:string; type:string; status:string; image:string; description:string; adult:number; episodeCount:number; createdAt:string }[];
  vip: VipSettings;
  social: Record<string,string>;
};
type VipSettings = { bankName:string; accountNumber:string; accountHolder:string; promotion:string; globalDiscount:number; accentColor:string };
const defaultVip: VipSettings = { bankName:"Хаан банк", accountNumber:"0000 0000 0000", accountHolder:"Зураас ХХК", promotion:"", globalDiscount:0, accentColor:"#8b6cf6" };

function ContentLibraryPanel({items,type,onTypeChange,onCreate,onOpen}:{items:AdminData["contents"];type:"anime"|"manga";onTypeChange:(type:"anime"|"manga")=>void;onCreate:()=>void;onOpen:(id:string)=>void}){
  const [query,setQuery]=useState("");
  const filtered=items.filter(item=>item.type===type&&item.title.toLowerCase().includes(query.trim().toLowerCase()));
  const animeCount=items.filter(item=>item.type==="anime").length;
  const mangaCount=items.filter(item=>item.type!=="anime").length;
  return <section className="admin-section content-library-panel"><header className="content-library-head"><div><small>КОНТЕНТЫН САН</small><h2>Анимэ, манга</h2><p>Бүтээлээ сонгоод анги эсвэл бүлгийг нь удирдана.</p></div><button onClick={onCreate}>＋ Шинэ бүтээл нэмэх</button></header><div className="content-list-tools"><nav><button className={type==="anime"?"active":""} onClick={()=>onTypeChange("anime")}>Анимэ <b>{animeCount}</b></button><button className={type==="manga"?"active":""} onClick={()=>onTypeChange("manga")}>Манга <b>{mangaCount}</b></button></nav><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Бүтээлийн нэрээр хайх..."/></label></div><div className="content-list"><div className="content-list-heading"><span>Бүтээл</span><span>Төлөв</span><span>{type==="anime"?"Анги":"Бүлэг"}</span><span>Нэмэгдсэн</span><span/></div>{filtered.length?filtered.map(item=><button className="content-list-row" key={item.id} onClick={()=>onOpen(item.id)}><span className="content-list-title"><img src={item.image} alt=""/><i><b>{item.title}</b><small>{item.type.toUpperCase()}{item.adult?" · +18":""}</small></i></span><span><em className={`content-status ${item.status.toLowerCase()}`}>{item.status}</em></span><strong>{item.episodeCount||0}</strong><time>{item.createdAt?.slice(0,10)||"—"}</time><i className="content-list-arrow">›</i></button>):<div className="content-list-empty"><b>{type==="anime"?"Анимэ":"Манга"} олдсонгүй</b><span>Шинэ бүтээл нэмэх товчоор эхний бүтээлээ оруулна уу.</span></div>}</div></section>
}

export function AdminDashboard() {
  const [tab,setTab]=useState("content"); const [data,setData]=useState<AdminData|null>(null); const [toast,setToast]=useState("");
  const [contentType,setContentType]=useState<"anime"|"manga">("anime"); const [contentView,setContentView]=useState<"list"|"create">("list"); const [selected,setSelected]=useState<string|null>(null); const [selectedInfo,setSelectedInfo]=useState<any>(null); const [previews,setPreviews]=useState<string[]>([]);
  const [vip,setVip]=useState<VipSettings>(defaultVip); const [userSearch,setUserSearch]=useState(""); const [grantUser,setGrantUser]=useState<AdminData["users"][number]|null>(null);
  const [metric,setMetric]=useState<"views"|"users"|"revenue"|"bookmarks">("views"); const [period,setPeriod]=useState("7"); const [social,setSocial]=useState<Record<string,string>>({facebook:"",instagram:"",youtube:"",discord:"",telegram:""});
  const load=()=>fetch("/api/app/admin").then(r=>r.json()).then((value:AdminData)=>{setData(value);if(value.vip)setVip(value.vip);if(value.social)setSocial(value.social);}).catch(()=>null);
  useEffect(()=>{document.title="Удирдлага";void load()},[]); const notify=(text:string)=>{setToast(text);setTimeout(()=>setToast(""),2500)};
  const nav=[{id:"content",n:"01",icon:"▣",label:"Анимэ, манга нэмэх"},{id:"comments",n:"02",icon:"◌",label:"Сэтгэгдэл"},{id:"users",n:"03",icon:"♙",label:"Хэрэглэгч"},{id:"membership",n:"04",icon:"♔",label:"Гишүүнчлэл"},{id:"analytics",n:"05",icon:"⌁",label:"Хандалт"},{id:"social",n:"06",icon:"◎",label:"Сошиал хаяг"}];
  const submitContent=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));body.type=contentType;await fetch("/api/app/admin/content",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});e.currentTarget.reset();notify(`${contentType==="anime"?"Анимэ":"Манга"} нэмэгдлээ`);setContentView("list");load();};
  const importAniList=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const id=new FormData(form).get("anilistId");const r=await fetch(`/api/app/admin/anilist?id=${id}&type=${contentType}`);const json=await r.json();if(!json.item)return notify("AniList мэдээлэл олдсонгүй");const item=json.item;(form.elements.namedItem("title") as HTMLInputElement).value=item.title.english||item.title.romaji;(form.elements.namedItem("description") as HTMLTextAreaElement).value=item.description||"";(form.elements.namedItem("status") as HTMLSelectElement).value=item.status==="FINISHED"?"Completed":item.status==="HIATUS"?"Hiatus":"Ongoing";(form.elements.namedItem("image") as HTMLInputElement).value=item.coverImage.extraLarge||"";(form.elements.namedItem("originalTitle") as HTMLInputElement).value=item.title.native||item.title.romaji;(form.elements.namedItem("year") as HTMLInputElement).value=String(item.startDate.year||2026);(form.elements.namedItem("genres") as HTMLInputElement).value=(item.genres||[]).join(", ");if(contentType==="manga")(form.elements.namedItem("adult") as HTMLInputElement).checked=Boolean(item.isAdult);notify("AniList-ээс мэдээлэл орлоо");};
  const openContent=async(id:string)=>{setSelected(id);const r=await fetch(`/api/app/admin/content/${id}`);setSelectedInfo(await r.json());};
  const addEpisode=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);fd.set("contentId",selected||"");const r=await fetch("/api/app/admin/episode",{method:"POST",body:fd});if(!r.ok)return notify("Файл оруулахад алдаа гарлаа");form.reset();setPreviews([]);notify("Анги / бүлэг амжилттай нэмэгдлээ");if(selected)openContent(selected);load();};
  const saveVip=async()=>{await fetch("/api/app/admin/vip",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(vip)});notify("Гишүүнчлэлийн тохиргоо хадгалагдлаа");load();};
  const addPackage=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const body=Object.fromEntries(new FormData(form));const r=await fetch("/api/app/admin/package",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok)return notify("Багц нэмэгдсэнгүй");form.reset();notify("Төлбөрийн багц нэмэгдлээ");load();};
  const editPackage=async(p:AdminData["packages"][number])=>{const name=window.prompt("Багцын нэр",p.name);if(name===null)return;const days=window.prompt("Хугацаа / хоног",String(p.durationDays));if(days===null)return;const price=window.prompt("Үнэ / ₮",String(p.price));if(price===null)return;if(!name.trim()||Number(days)<=0||Number(price)<0)return notify("Багцын мэдээллээ зөв оруулна уу");const r=await fetch(`/api/app/admin/package/${p.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({name:name.trim(),durationDays:Number(days),price:Number(price)})});if(!r.ok)return notify("Багц засагдсангүй");notify("Багц шинэчлэгдлээ");load();};
  const deletePackage=async(p:AdminData["packages"][number])=>{if(!window.confirm(`“${p.name}” багцыг устгах уу?`))return;const r=await fetch(`/api/app/admin/package/${p.id}`,{method:"DELETE"});if(!r.ok)return notify("Багц устгагдсангүй");notify("Багц устгагдлаа");load();};
  const grantVip=async(days:number)=>{if(!grantUser)return;await fetch("/api/app/admin/grant-vip",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:grantUser.email,days})});notify("VIP эрх амжилттай олголоо");setGrantUser(null);load();};
  const saveSocial=async(e:FormEvent)=>{e.preventDefault();await fetch("/api/app/admin/social",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(social)});notify("Сошиал хаягууд хадгалагдлаа");};
  const users=useMemo(()=>data?.users.filter(u=>`${u.usercode} ${u.email} ${u.displayName}`.toLowerCase().includes(userSearch.toLowerCase()))||[],[data,userSearch]);
  const discounted=(price:number)=>Math.round(price*(1-(Number(vip.globalDiscount)||0)/100));
  return <div className="admin-shell-full"><aside className="admin-nav"><a href="/admin" className="admin-brand"><img src="/logo-transparent.png" alt=""/><div><b>ЗУРААС</b><small>CONTROL CENTER</small></div></a><p>УДИРДЛАГА</p><nav>{nav.map(item=><button className={tab===item.id?"active":""} onClick={()=>{setTab(item.id);setSelected(null);setContentView("list")}} key={item.id}><small>{item.n}</small><i>{item.icon}</i><span>{item.label}</span></button>)}</nav><div className="admin-account"><span>AD</span><div><b>Администратор</b><small>Бүх эрхтэй</small></div></div><a className="back-to-site" href="/">← Үндсэн сайт</a></aside><main className="admin-workspace"><header className="admin-top"><div><small>ЗУРААС / {nav.find(n=>n.id===tab)?.label.toUpperCase()}</small><h1>{nav.find(n=>n.id===tab)?.label}</h1></div><div><span className="system-online">● Систем хэвийн</span><a href="/">Сайт руу ↗</a></div></header>{toast&&<div className="save-toast">✓ {toast}</div>}
  {tab==="content"&&!selected&&contentView==="list"&&<ContentLibraryPanel items={data?.contents||[]} type={contentType} onTypeChange={setContentType} onCreate={()=>setContentView("create")} onOpen={openContent}/>}
  {tab==="content"&&!selected&&contentView==="create"&&<section className="admin-section content-create-mode"><button className="admin-back" onClick={()=>setContentView("list")}>← Бүтээлийн жагсаалт</button><div className="content-kind-tabs"><button className={contentType==="anime"?"active":""} onClick={()=>setContentType("anime")}>Анимэ нэмэх</button><button className={contentType==="manga"?"active":""} onClick={()=>setContentType("manga")}>Манга нэмэх</button></div><div className="content-admin-grid"><form className="admin-form advanced-content-form" onSubmit={submitContent}><div className="section-title"><div><small>АЛХАМ 1</small><h2>{contentType==="anime"?"Шинэ анимэ":"Шинэ манга"}</h2></div><span>{contentType==="anime"?"ANIME":"MANGA"}</span></div><div className="anilist-import"><label>AniList ID<input name="anilistId" type="number" placeholder="Жишээ: 16498"/></label><button type="button" onClick={e=>importAniList({preventDefault:()=>{},currentTarget:(e.currentTarget.closest("form") as HTMLFormElement)} as FormEvent<HTMLFormElement>)}>AniList-ээс import</button></div><label>Нэр<input name="title" required placeholder="Бүтээлийн нэр"/></label><input name="originalTitle" type="hidden"/><input name="year" type="hidden" defaultValue="2026"/><input name="genres" type="hidden"/><input name="image" type="hidden"/><label>Товч танилцуулга<textarea name="description" required placeholder="Бүтээлийн тухай товч тайлбар..."/></label><label>Төлөв<select name="status"><option>Ongoing</option><option>Completed</option><option>Hiatus</option></select></label>{contentType==="manga"&&<label className="check-label"><input name="adult" type="checkbox" value="true"/> +18 контент</label>}<button type="submit">＋ {contentType==="anime"?"Анимэ":"Манга"} нэмэх</button></form><aside className="existing-content"><div className="section-title"><div><small>АЛХАМ 2</small><h2>Анги нэмэх бүтээлээ сонгох</h2></div><b>{data?.contents.length||0}</b></div><div>{data?.contents.length?data.contents.map(item=><button key={item.id} onClick={()=>openContent(item.id)}><img src={item.image}/><span><b>{item.title}</b><small>{item.type.toUpperCase()} · {item.status}{item.adult?" · +18":""}</small></span><i>›</i></button>):<p className="empty-admin-copy">Эхлээд анимэ эсвэл манга нэмнэ үү.</p>}</div></aside></div></section>}
  {tab==="content"&&selected&&<section className="admin-section"><button className="admin-back" onClick={()=>{setSelected(null);setSelectedInfo(null)}}>← Бүтээлийн жагсаалт</button><div className="content-editor-head"><img src={selectedInfo?.content?.image}/><div><small>{selectedInfo?.content?.type?.toUpperCase()}</small><h2>{selectedInfo?.content?.title}</h2><p>{selectedInfo?.content?.description}</p></div></div><div className="episode-editor-grid"><form id="episode-upload-form" className="admin-form" onSubmit={addEpisode}><div className="section-title"><div><small>ШИНЭ КОНТЕНТ</small><h2>{selectedInfo?.content?.type==="anime"?"Анги нэмэх":"Бүлэг нэмэх"}</h2></div></div><label>{selectedInfo?.content?.type==="anime"?"Ангийн":"Бүлгийн"} дугаар<input name="number" type="number" step="0.1" required/></label><label>Унших / үзэх эрх<select name="access"><option value="registered">Бүртгэлтэй хэрэглэгч</option><option value="vip">Зөвхөн VIP</option></select></label><label>Нийтлэх он, цаг <small>(заавал биш)</small><input name="publishAt" type="datetime-local"/></label><button type="submit">Хадгалах</button></form><div className="upload-panel"><div className="section-title"><div><small>МЕДИА</small><h2>{selectedInfo?.content?.type==="anime"?"Видео upload":"Зургууд upload"}</h2></div></div><label className="upload-drop">⇧<b>Файл сонгох</b><span>{selectedInfo?.content?.type==="anime"?"MP4, WebM видео":"JPG, PNG зургууд"}</span><input form="episode-upload-form" name="files" type="file" accept={selectedInfo?.content?.type==="anime"?"video/*":"image/*"} multiple={selectedInfo?.content?.type!=="anime"} onChange={e=>{const files=Array.from(e.target.files||[]);setPreviews(files.map(URL.createObjectURL));const target=document.querySelector('.episode-editor-grid form input[type=file]') as HTMLInputElement|null;if(target){const dt=new DataTransfer();files.forEach(f=>dt.items.add(f));target.files=dt.files;}}}/></label><h3>Preview</h3><div className={selectedInfo?.content?.type==="anime"?"video-preview":"image-previews"}>{previews.length?previews.map(url=>selectedInfo?.content?.type==="anime"?<video key={url} src={url} controls/>:<img key={url} src={url}/>):<p>Сонгосон файл энд харагдана.</p>}</div></div></div><div className="episode-history"><h2>Нэмэгдсэн анги, бүлгүүд</h2>{selectedInfo?.episodes?.map((ep:any)=><div key={ep.id}><b>#{ep.number}</b><span>{ep.access==="vip"?"VIP":"Бүртгэлтэй"}</span><small>{ep.publishAt||"Шууд нийтэлсэн"}</small></div>)}</div></section>}
  {tab==="comments"&&<section className="admin-section"><div className="section-title"><div><small>МОДЕРАЦИ</small><h2>Бүх сэтгэгдэл</h2></div><b>{data?.comments.length||0}</b></div><div className="comment-admin-list">{data?.comments.length?data.comments.map(c=><article key={c.id}><span>{c.displayName.slice(0,2)}</span><div><b>{c.displayName}<small> / {c.contentId}</small></b><p>{c.body}</p><time>{c.createdAt}</time></div><button>•••</button></article>):<div className="no-admin-data">Сэтгэгдэл байхгүй байна.</div>}</div></section>}
  {tab==="users"&&<section className="admin-section"><div className="section-title"><div><small>ХЭРЭГЛЭГЧИЙН УДИРДЛАГА</small><h2>Бүртгэлтэй хэрэглэгчид</h2></div><input value={userSearch} onChange={e=>setUserSearch(e.target.value)} placeholder="Нэр, и-мэйл, 6 оронтой код..."/></div><div className="admin-table user-code-table"><div className="table-head"><span>Хэрэглэгч</span><span>Usercode</span><span>VIP эрх</span><span></span></div>{users.map(u=><button key={u.id} onClick={()=>setGrantUser(u)}><span className="user-cell"><i>{u.displayName.slice(0,2)}</i><b>{u.displayName}<small>{u.email}</small></b></span><code>{u.usercode}</code><span>{u.vipUntil||"Эрхгүй"}</span><i>Эрх өгөх ›</i></button>)}</div>{grantUser&&<div className="grant-modal"><div><button onClick={()=>setGrantUser(null)}>×</button><span>{grantUser.displayName.slice(0,2)}</span><h2>{grantUser.displayName}</h2><code>{grantUser.usercode}</code><p>VIP эрхийн хугацааг сонгоно уу.</p><div><button onClick={()=>grantVip(7)}>7 хоног</button><button onClick={()=>grantVip(30)}>30 хоног</button><button onClick={()=>grantVip(365)}>1 жил</button></div></div></div>}</section>}
  {tab==="membership"&&<section className="admin-section membership-rebuild"><div className="membership-settings-grid"><div><form className="admin-form" onSubmit={e=>{e.preventDefault();saveVip()}}><div className="section-title"><div><small>ТӨЛБӨР ХҮЛЭЭН АВАХ</small><h2>Банкны мэдээлэл</h2></div></div><label>Банкны нэр<input value={vip.bankName} onChange={e=>setVip({...vip,bankName:e.target.value})}/></label><label>Дансны дугаар<input value={vip.accountNumber} onChange={e=>setVip({...vip,accountNumber:e.target.value})}/></label><label>Данс эзэмшигч<input value={vip.accountHolder} onChange={e=>setVip({...vip,accountHolder:e.target.value})}/></label><button>Хадгалах</button></form><form className="admin-form promo-form" onSubmit={e=>{e.preventDefault();saveVip()}}><div className="section-title"><div><small>БҮХ БАГЦАД ҮЙЛЧИЛНЭ</small><h2>Хямдрал</h2></div></div><label>Нийт хямдралын хувь<input type="number" min="0" max="100" value={vip.globalDiscount} onChange={e=>setVip({...vip,globalDiscount:Number(e.target.value)})}/></label><button>Хямдрал зарлах</button></form><form className="admin-form" onSubmit={addPackage}><div className="section-title"><div><small>ТӨЛБӨРИЙН БАГЦ</small><h2>Шинэ багц нэмэх</h2></div></div><label>Багцын нэр<input name="name" required placeholder="Сарын эрх"/></label><div className="form-row"><label>Хугацаа / хоног<input name="durationDays" type="number" required defaultValue="30"/></label><label>Үнэ / ₮<input name="price" type="number" required defaultValue="12900"/></label></div><button>＋ Багц нэмэх</button></form></div><aside className="discount-live-preview"><div className="section-title"><div><small>LIVE PREVIEW</small><h2>Хямдарсан багцууд</h2></div><span>LIVE</span></div><div>{data?.packages.map(p=><article key={p.id}><span><b>{p.name}</b><small>{p.durationDays} хоног</small></span><div className="package-price"><del>{vip.globalDiscount?p.price.toLocaleString()+"₮":""}</del><strong>{discounted(p.price).toLocaleString()}₮</strong></div><div className="package-row-actions"><button type="button" onClick={()=>editPackage(p)}>Засах</button><button type="button" className="danger" onClick={()=>deletePackage(p)}>Устгах</button></div></article>)}</div></aside></div></section>}
  {tab==="analytics"&&<section className="admin-section"><div className="metric-grid clickable-metrics"><button className={metric==="views"?"active":""} onClick={()=>setMetric("views")}><i>↗</i><small>НИЙТ ХАНДАЛТ</small><strong>{data?.analytics.visits||0}</strong><span>Дэлгэрэнгүй ›</span></button><button className={metric==="users"?"active":""} onClick={()=>setMetric("users")}><i>♙</i><small>БҮРТГҮҮЛСЭН ХЭРЭГЛЭГЧ</small><strong>{data?.analytics.users||0}</strong><span>Дэлгэрэнгүй ›</span></button><button className={metric==="revenue"?"active":""} onClick={()=>setMetric("revenue")}><i>₮</i><small>НИЙТ ОРЛОГО</small><strong>{(data?.analytics.revenue||0).toLocaleString()}₮</strong><span>Дэлгэрэнгүй ›</span></button><button className={metric==="bookmarks"?"active":""} onClick={()=>setMetric("bookmarks")}><i>▥</i><small>BOOKMARK МАНГА</small><strong>{data?.analytics.bookmarks||0}</strong><span>Дэлгэрэнгүй ›</span></button></div><div className="period-analytics"><header><div><small>ХУГАЦААНЫ ҮЗҮҮЛЭЛТ</small><h2>{metric==="views"?"Хандалт":metric==="users"?"Шинэ хэрэглэгч":metric==="revenue"?"Орлого":"Хадгалсан манга"}</h2></div><nav>{["1","7","30"].map(d=><button className={period===d?"active":""} onClick={()=>setPeriod(d)} key={d}>{d} хоног</button>)}</nav></header><strong>{metric==="revenue"?(data?.periods?.[period]?.[metric]||0).toLocaleString()+"₮":data?.periods?.[period]?.[metric]||0}</strong><div className="wide-chart">{[38,54,42,67,58,82,76,91,68,79,62,87].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div></section>}
  {tab==="social"&&<section className="admin-section social-section"><form className="admin-form" onSubmit={saveSocial}><div className="section-title"><div><small>ХОЛБООСУУД</small><h2>Сошиал хаяг тохируулах</h2></div></div>{[["facebook","Facebook"],["instagram","Instagram"],["youtube","YouTube"],["discord","Discord"],["telegram","Telegram"]].map(([key,label])=><label key={key}>{label}<input type="url" value={social[key]||""} onChange={e=>setSocial({...social,[key]:e.target.value})} placeholder={`https://${key}.com/zuraas`}/></label>)}<button>Сошиал хаягууд хадгалах</button></form><aside><span>◎</span><h2>Нэг дор удирдах</h2><p>Энд тохируулсан холбоосууд үндсэн сайтын сошиал хэсэгт автоматаар ашиглагдана.</p></aside></section>}
  </main></div>;
}
