"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { FormEvent, MouseEvent } from "react";
import { AlertTriangle, ArrowLeft, BookOpen, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronsUp, Expand, Gauge, List, Minus, PanelTop, Play, Plus, Settings, Square, X } from "lucide-react";

type ReadingMode="vertical"|"paged";
type Drawer="chapters"|"settings"|null;
const issueTypes=["Зураг ачаалахгүй байна","Зургууд дутуу / Дараалал алдагдсан","Буруу бүлэг орсон байна","Орчуулга эсвэл текстийн алдаатай","Бусад асуудал"];

export function MangaReader({contentId,title,chapter,chapters,pages,locked}:{contentId:string;title:string;chapter:number;chapters:number[];pages:string[];locked:boolean}){
  const [controls,setControls]=useState(true);const [drawer,setDrawer]=useState<Drawer>(null);const [mode,setMode]=useState<ReadingMode>("vertical");const [speed,setSpeed]=useState(2);const [autoScroll,setAutoScroll]=useState(false);const [zoom,setZoom]=useState(100);const [pageIndex,setPageIndex]=useState(0);const [reportOpen,setReportOpen]=useState(false);const [reportState,setReportState]=useState<"idle"|"sending"|"sent">("idle");const lastScroll=useRef(0);
  const chapterIndex=chapters.indexOf(chapter);const newer=chapterIndex>0?chapters[chapterIndex-1]:null;const older=chapterIndex>=0&&chapterIndex<chapters.length-1?chapters[chapterIndex+1]:null;
  const pageLabel=useMemo(()=>`${Math.min(pageIndex+1,pages.length||1)} / ${pages.length||1}`,[pageIndex,pages.length]);
  useEffect(()=>{const saved=localStorage.getItem("zuraas-reader-mode");if(saved==="paged"||saved==="vertical")setMode(saved);const savedSpeed=Number(localStorage.getItem("zuraas-reader-speed"));if(savedSpeed>=1&&savedSpeed<=5)setSpeed(savedSpeed);document.title=`${title} · Бүлэг ${chapter}`;fetch("/api/app/history",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contentId,progress:chapter})}).catch(()=>null)},[contentId,title,chapter]);
  useEffect(()=>{const onScroll=()=>{const current=window.scrollY;if(Math.abs(current-lastScroll.current)>10){setControls(current<lastScroll.current||current<30);lastScroll.current=current}};window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
  useEffect(()=>{if(!autoScroll||mode!=="vertical")return;let frame=0;let previous=performance.now();const tick=(time:number)=>{const delta=Math.min(time-previous,32);previous=time;window.scrollBy(0,(speed*.55*delta)/16);if(window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-4){setAutoScroll(false);return}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[autoScroll,speed,mode]);
  useEffect(()=>{if(drawer!=="chapters")return;const input=document.querySelector<HTMLInputElement>(".reader-chapter-list input");if(!input)return;const filter=()=>{const query=input.value.trim().toLowerCase();document.querySelectorAll<HTMLElement>(".reader-chapter-list>button").forEach(button=>{button.hidden=Boolean(query&&!button.textContent?.toLowerCase().includes(query))})};input.addEventListener("input",filter);return()=>input.removeEventListener("input",filter)},[drawer]);
  const setReadingMode=(value:ReadingMode)=>{setMode(value);localStorage.setItem("zuraas-reader-mode",value);setAutoScroll(false);setPageIndex(0);window.scrollTo({top:0})};
  const setScrollSpeed=(value:number)=>{setSpeed(value);localStorage.setItem("zuraas-reader-speed",String(value))};
  const goChapter=(value:number|null)=>{if(value!==null)window.location.assign(`/read/${contentId}/${value}`)};
  const toggleFullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{/* Browser may block fullscreen. */}};
  const readerClick=(event:MouseEvent<HTMLElement>)=>{if(mode==="vertical"){setControls(value=>!value);return}const ratio=event.clientX/window.innerWidth;if(ratio<.35)setPageIndex(value=>Math.max(0,value-1));else if(ratio>.65)setPageIndex(value=>Math.min(pages.length-1,value+1));else setControls(value=>!value)};
  const submitReport=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setReportState("sending");const form=new FormData(event.currentTarget);const response=await fetch("/api/app/reports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contentId,chapterNumber:chapter,issueType:form.get("issueType"),details:form.get("details")})});if(response.ok){setReportState("sent");setTimeout(()=>{setReportOpen(false);setReportState("idle")},1100)}else setReportState("idle")};
  return <main className={`manga-reader mode-${mode} ${controls?"controls-visible":"controls-hidden"}`}>
    <header className="reader-topbar"><a className="reader-icon-button reader-back" href={`/title/${contentId}`} aria-label="Буцах"><ArrowLeft size={21}/></a><div className="reader-title"><b>{title}</b><small>БҮЛЭГ {chapter}</small></div><div className="reader-chapter-control"><button disabled={older===null} onClick={()=>goChapter(older)} aria-label="Өмнөх бүлэг"><ChevronLeft size={18}/></button><button className="chapter-current" onClick={()=>setDrawer(drawer==="chapters"?null:"chapters")}><span><small>БҮЛЭГ</small><b>{chapter}</b></span><List size={17}/><ChevronDown size={14}/></button><button disabled={newer===null} onClick={()=>goChapter(newer)} aria-label="Дараагийн бүлэг"><ChevronRight size={18}/></button></div><div className="reader-actions"><button onClick={()=>setReportOpen(true)} aria-label="Алдаа мэдэгдэх" title="Алдаа мэдэгдэх"><AlertTriangle size={20}/></button><button onClick={()=>setDrawer(drawer==="settings"?null:"settings")} aria-label="Унших тохиргоо"><Settings size={20}/></button><button onClick={toggleFullscreen} aria-label="Дэлгэц дүүргэх"><Expand size={20}/></button></div>
    </header>
    {locked?<section className="reader-locked"><span><BookOpen size={35}/></span><h1>VIP бүлэг</h1><p>Энэ бүлгийг уншихын тулд VIP эрх шаардлагатай.</p><a href="/vip">VIP эрх авах</a></section>:pages.length?<section className="reader-pages" onClick={readerClick} style={{"--reader-zoom":`${zoom/100}`} as React.CSSProperties}>{mode==="vertical"?pages.map((src,index)=><img src={src} alt={`Бүлэг ${chapter} · Хуудас ${index+1}`} key={`${src}-${index}`} draggable={false}/>):<div className="reader-paged-stage"><img src={pages[pageIndex]} alt={`Бүлэг ${chapter} · Хуудас ${pageIndex+1}`} draggable={false}/><button className="page-hit previous" onClick={event=>{event.stopPropagation();setPageIndex(value=>Math.max(0,value-1))}} disabled={pageIndex===0} aria-label="Өмнөх хуудас"><ChevronLeft/></button><button className="page-hit next" onClick={event=>{event.stopPropagation();setPageIndex(value=>Math.min(pages.length-1,value+1))}} disabled={pageIndex===pages.length-1} aria-label="Дараагийн хуудас"><ChevronRight/></button><span className="page-counter">{pageLabel}</span></div>}</section>:<section className="reader-locked"><span><BookOpen size={35}/></span><h1>Зураг ороогүй байна</h1><p>Энэ бүлгийн хуудсууд удахгүй нэмэгдэнэ.</p><button onClick={()=>setReportOpen(true)}>Алдаа мэдэгдэх</button></section>}
    {!locked&&<aside className="reader-float-tools"><button onClick={()=>setZoom(value=>Math.min(150,value+10))} aria-label="Томруулах"><Plus size={20}/></button><button onClick={()=>setZoom(value=>Math.max(60,value-10))} aria-label="Жижигрүүлэх"><Minus size={20}/></button><button className={autoScroll?"active":""} onClick={()=>setAutoScroll(value=>!value)} disabled={mode!=="vertical"} aria-label={autoScroll?"Автомат гүйлгэлт зогсоох":"Автоматаар гүйлгэх"}>{autoScroll?<Square size={17}/>:<Play size={20}/>}</button><i/><button onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} aria-label="Дээш очих"><ChevronsUp size={20}/></button></aside>}
    {drawer&&<button className="reader-drawer-backdrop" aria-label="Цэс хаах" onClick={()=>setDrawer(null)}/>}<aside className={`reader-drawer ${drawer?"open":""}`}><header><div><h2>{drawer==="chapters"?"БҮЛГҮҮД":"ТОХИРГОО"}</h2><small>{drawer==="chapters"?`НИЙТ ${chapters.length}`:"УНШИХ ОРЧИН"}</small></div><button onClick={()=>setDrawer(null)} aria-label="Хаах"><X size={20}/></button></header>{drawer==="chapters"?<div className="reader-chapter-list"><label><List size={17}/><input placeholder="Дугаар эсвэл нэрээр хайх..."/></label>{chapters.map(value=><button className={value===chapter?"active":""} onClick={()=>goChapter(value)} key={value}><b>Бүлэг {value}</b>{value===chapter&&<span><Check size={15}/></span>}</button>)}</div>:<div className="reader-settings"><section><small>УНШИХ ХЭЛБЭР</small><div className="reader-mode-options"><button className={mode==="vertical"?"active":""} onClick={()=>setReadingMode("vertical")}><PanelTop size={21}/><span><b>Босоо</b><small>Доош гүйлгэж унших</small></span>{mode==="vertical"&&<Check size={17}/>}</button><button className={mode==="paged"?"active":""} onClick={()=>setReadingMode("paged")}><BookOpen size={21}/><span><b>Хуудсаар</b><small>Нэг нэг хуудсаар</small></span>{mode==="paged"&&<Check size={17}/>}</button></div></section><section><small>ГҮЙЛГЭХ ХУРД</small><div className="reader-speed-head"><Gauge size={18}/><span>Автомат гүйлгэлт</span><b>{speed}</b></div><input type="range" min="1" max="5" step="1" value={speed} onChange={event=>setScrollSpeed(Number(event.target.value))}/><div className="speed-labels"><span>Удаан</span><span>Хурдан</span></div><button className={`auto-scroll-toggle ${autoScroll?"active":""}`} disabled={mode!=="vertical"} onClick={()=>setAutoScroll(value=>!value)}>{autoScroll?<><Square size={16}/> Зогсоох</>:<><Play size={17}/> Автоматаар гүйлгэх</>}</button></section></div>}</aside>
    {reportOpen&&<div className="reader-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setReportOpen(false)}}><form className="reader-report-modal" onSubmit={submitReport}><header><AlertTriangle size={20}/><h2>АЛДАА МЭДЭЭЛЭХ</h2><button type="button" onClick={()=>setReportOpen(false)}><X size={18}/></button></header>{reportState==="sent"?<div className="report-sent"><span><Check size={25}/></span><b>Мэдээлэл илгээгдлээ</b><p>Бид удахгүй шалгаж засах болно.</p></div>:<><fieldset><legend>АЛДААНЫ ТӨРӨЛ</legend>{issueTypes.map((type,index)=><label key={type}><input type="radio" name="issueType" value={type} defaultChecked={index===0}/><span>{type}</span></label>)}</fieldset><label className="report-details">ДЭЛГЭРЭНГҮЙ ТАЙЛБАР<textarea name="details" placeholder="Алдааны талаар нэмэлт тайлбар бичнэ үү..."/></label><footer><button type="button" onClick={()=>setReportOpen(false)}>Цуцлах</button><button disabled={reportState==="sending"}>{reportState==="sending"?"Илгээж байна...":"Илгээх"}</button></footer></>}</form></div>}
  </main>;
}
