"use client";

import { useEffect,useState } from "react";
import type { FormEvent } from "react";
import { Camera,ChevronRight,Clock3,KeyRound,LogOut,MonitorSmartphone,ShieldCheck,UserRound } from "lucide-react";

type SettingsData={
  profile:{displayName:string;authEmail:string;contactEmail:string;usercode:string;vipUntil:string|null;avatarUrl:string|null;coverUrl:string|null};
  devices:{deviceId:string;label:string;createdAt:string;lastSeenAt:string}[];
  currentDeviceId:string;
  payments:{id:number;days:number;source:string;grantedAt:string;expiresAt:string|null}[];
};
type SettingsTab="profile"|"security"|"devices"|"payments";

const dateTime=(value:string|null)=>value?new Intl.DateTimeFormat("mn-MN",{year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value.replace(" ","T")+(/Z$/.test(value)?"":"Z"))):"—";

export function SettingsPage(){
  const [data,setData]=useState<SettingsData|null>(null);const [tab,setTab]=useState<SettingsTab>("profile");const [displayName,setDisplayName]=useState("");const [contactEmail,setContactEmail]=useState("");const [avatar,setAvatar]=useState<File|null>(null);const [cover,setCover]=useState<File|null>(null);const [avatarPreview,setAvatarPreview]=useState("");const [coverPreview,setCoverPreview]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  const load=async()=>{const response=await fetch("/api/app/settings");if(response.status===401){window.location.assign("/signout-with-chatgpt?return_to=/");return}const value=await response.json() as SettingsData;setData(value);setDisplayName(value.profile.displayName);setContactEmail(value.profile.contactEmail);setAvatarPreview(value.profile.avatarUrl||"");setCoverPreview(value.profile.coverUrl||"")};
  useEffect(()=>{document.title="Тохиргоо";void load()},[]);
  const pick=(file:File|undefined,kind:"avatar"|"cover")=>{if(!file)return;const url=URL.createObjectURL(file);if(kind==="avatar"){setAvatar(file);setAvatarPreview(url)}else{setCover(file);setCoverPreview(url)}};
  const saveProfile=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setMessage("");const body=new FormData();body.set("displayName",displayName);body.set("contactEmail",contactEmail);if(avatar)body.set("avatar",avatar);if(cover)body.set("cover",cover);const response=await fetch("/api/app/settings/profile",{method:"POST",body});const result=await response.json();setBusy(false);if(!response.ok){setMessage(result.error||"Хадгалахад алдаа гарлаа");return}setAvatar(null);setCover(null);setMessage("Хувийн мэдээлэл хадгалагдлаа");await load()};
  const logoutOthers=async()=>{if(!window.confirm("Бусад бүх төхөөрөмжөөс гарах уу?"))return;setBusy(true);const response=await fetch("/api/app/settings/devices/logout-others",{method:"POST"});setBusy(false);if(response.ok){setMessage("Бусад төхөөрөмжүүдээс гарлаа");await load()}else setMessage("Төхөөрөмжөөс гаргахад алдаа гарлаа")};
  const nav=[{id:"profile" as const,label:"Хувийн мэдээлэл",icon:UserRound},{id:"security" as const,label:"Аюулгүй байдал",icon:ShieldCheck},{id:"devices" as const,label:"Идэвхтэй төхөөрөмж",icon:MonitorSmartphone,badge:data?.devices.length},{id:"payments" as const,label:"Төлбөрийн түүх",icon:Clock3}];
  if(!data)return <main className="settings-page"><div className="settings-loading">Тохиргоо ачаалж байна...</div></main>;
  return <main className="settings-page"><header className="settings-title"><div><small>БҮРТГЭЛ</small><h1>Тохиргоо</h1><p>Хувийн мэдээлэл, аюулгүй байдал болон төхөөрөмжүүдээ удирдана.</p></div></header>{message&&<div className="settings-message">{message}</div>}<div className="settings-layout"><aside className="settings-nav">{nav.map(({id,label,icon:Icon,badge})=><button className={tab===id?"active":""} onClick={()=>{setTab(id);setMessage("")}} key={id}><Icon size={17}/><span>{label}</span>{badge!==undefined&&<b>{badge}</b>}<ChevronRight size={15}/></button>)}</aside><section className="settings-content">{tab==="profile"&&<form className="profile-settings" onSubmit={saveProfile}><div className="settings-card profile-visual"><div className="profile-cover" style={coverPreview?{backgroundImage:`linear-gradient(0deg,rgba(8,10,14,.35),rgba(8,10,14,.08)),url(${coverPreview})`}:undefined}><label><Camera size={15}/> Ковер зураг солих<input type="file" accept="image/*" onChange={e=>pick(e.target.files?.[0],"cover")}/></label></div><div className="profile-avatar-wrap"><div className="profile-avatar-large">{avatarPreview?<img src={avatarPreview} alt="Нүүр зураг"/>:<span>{displayName.slice(0,2).toUpperCase()}</span>}<label aria-label="Нүүр зураг солих"><Camera size={15}/><input type="file" accept="image/*" onChange={e=>pick(e.target.files?.[0],"avatar")}/></label></div><div><h2>{displayName}</h2><p>{contactEmail}</p></div></div></div><div className="settings-card settings-form-card"><div className="settings-section-head"><UserRound size={19}/><div><h2>Хувийн мэдээлэл</h2><p>Сайтад харагдах нэр болон холбоо барих имэйл.</p></div></div><label>Хэрэглэгчийн нэр<input value={displayName} onChange={e=>setDisplayName(e.target.value)} minLength={2} maxLength={50} required/></label><label>Имэйл хаяг<input type="email" value={contactEmail} onChange={e=>setContactEmail(e.target.value)} required/><small>Нэвтрэх үндсэн имэйл: {data.profile.authEmail}</small></label><div className="settings-usercode"><small>USERCODE</small><code>{data.profile.usercode}</code><span>VIP эрх авахдаа гүйлгээний утга дээр энэ кодыг бичнэ.</span></div><div className="settings-form-actions"><span>Зураг JPG, PNG эсвэл WebP · 8MB хүртэл</span><button disabled={busy}>{busy?"Хадгалж байна...":"Өөрчлөлт хадгалах"}</button></div></div></form>}
    {tab==="security"&&<div className="settings-card security-card"><span><KeyRound size={25}/></span><div><small>НУУЦ ҮГ</small><h2>ChatGPT бүртгэлээр хамгаалагдсан</h2><p>Зураас нь таны нууц үгийг хадгалдаггүй. Нэвтрэх нууц үг болон хоёр шатлалт баталгаажуулалтыг ChatGPT бүртгэлийн аюулгүй байдлын тохиргооноос солино.</p><a href="https://chatgpt.com/" target="_blank" rel="noreferrer">ChatGPT аюулгүй байдлыг нээх <ChevronRight size={15}/></a></div></div>}
    {tab==="devices"&&<div className="settings-card"><div className="settings-section-head devices-head"><MonitorSmartphone size={20}/><div><h2>Идэвхтэй төхөөрөмж</h2><p>Одоогоор {data.devices.length} төхөөрөмжөөс нэвтэрсэн байна.</p></div><button onClick={logoutOthers} disabled={busy}><LogOut size={15}/> Бусад бүх төхөөрөмжөөс гарах</button></div><div className="device-list">{data.devices.map(device=><article key={device.deviceId}><i><MonitorSmartphone size={19}/></i><div><b>{device.label}</b><small>Сүүлд идэвхтэй: {dateTime(device.lastSeenAt)}</small></div>{device.deviceId===data.currentDeviceId?<span>Энэ төхөөрөмж</span>:<em>Идэвхтэй</em>}</article>)}</div></div>}
    {tab==="payments"&&<div className="settings-card"><div className="settings-section-head"><Clock3 size={20}/><div><h2>Төлбөрийн түүх</h2><p>VIP эрх орсон огноо, цаг болон дуусах хугацаа.</p></div></div>{data.payments.length?<div className="payment-history"><div><span>Эрхийн хугацаа</span><span>Орсон огноо</span><span>Дуусах огноо</span><span>Төлөв</span></div>{data.payments.map(payment=><article key={payment.id}><b>{payment.days} хоногийн VIP</b><time>{dateTime(payment.grantedAt)}</time><time>{dateTime(payment.expiresAt)}</time><span>{payment.expiresAt&&new Date(payment.expiresAt.replace(" ","T")+"Z")>new Date()?"Идэвхтэй":"Дууссан"}</span></article>)}</div>:<div className="settings-empty"><Clock3 size={27}/><b>Төлбөрийн түүх байхгүй</b><p>VIP эрх орсны дараа огноо, цаг энд харагдана.</p></div>}</div>}
  </section></div></main>;
}
