"use client";

import { useEffect, useMemo, useState } from "react";
import { Chrome } from "../components/Chrome";
import type { CatalogItem } from "../data/catalog";

function CatalogCard({item}:{item:CatalogItem}){const count=item.type==="anime"?`${item.episodes??0} АНГИ`:`${item.chapters??0} БҮЛЭГ`;return <a className="catalog-card" href={`/title/${item.id}`}><div className="catalog-poster"><img src={item.image} alt={item.title}/><b>{item.type==="anime"?"АНИМЭ":"МАНГА"}</b><span><small>{count}</small><small>★ {item.rating.toFixed(1)}</small></span></div><div><h2>{item.title}</h2><i>→</i><p>{item.type==="anime"?"АНИМЭ":"МАНХВА / МАНГА"} · {item.status.toUpperCase()}</p></div></a>}

export default function CatalogPage(){
  const [items,setItems]=useState<CatalogItem[]>([]);const [query,setQuery]=useState("");const [type,setType]=useState("all");const [genre,setGenre]=useState("all");const [status,setStatus]=useState("all");const [sort,setSort]=useState("newest");
  useEffect(()=>{const params=new URLSearchParams(window.location.search);setType(params.get("type")||"all");fetch("/api/catalog").then(r=>r.json()).then(data=>setItems(data.items||[])).catch(()=>setItems([]))},[]);
  const genres=useMemo(()=>Array.from(new Set(items.flatMap(item=>item.genres))).sort(),[items]);
  const filtered=useMemo(()=>{const needle=query.toLowerCase();const result=items.filter(item=>(!needle||`${item.title} ${item.originalTitle}`.toLowerCase().includes(needle))&&(type==="all"||(type==="manga"?item.type!=="anime":item.type===type))&&(genre==="all"||item.genres.includes(genre))&&(status==="all"||item.status.toLowerCase()===status.toLowerCase()));return result.sort((a,b)=>sort==="rating"?b.rating-a.rating:sort==="title"?a.title.localeCompare(b.title):b.year-a.year)},[items,query,type,genre,status,sort]);
  const chapters=filtered.reduce((sum,item)=>sum+(item.type==="anime"?(item.episodes||0):(item.chapters||0)),0);
  return <Chrome searchValue={query} onSearchChange={setQuery}><main className="catalog-page"><section className="catalog-filter-panel"><label className="catalog-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Бүтээлийн нэрээр хайх..."/></label><div className="catalog-filters"><label><small>АНГИЛАЛ</small><select value={type} onChange={e=>setType(e.target.value)}><option value="all">Бүгд</option><option value="anime">Анимэ</option><option value="manga">Манга</option></select></label><label><small>ТӨРӨЛ</small><select value={genre} onChange={e=>setGenre(e.target.value)}><option value="all">Бүгд</option>{genres.map(value=><option value={value} key={value}>{value}</option>)}</select></label><label><small>ТӨЛӨВ</small><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Бүгд</option><option value="On-Going">Ongoing</option><option value="Completed">Completed</option><option value="Hiatus">Hiatus</option></select></label><label><small>ЭРЭМБЭ</small><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Шинээр нэмэгдсэн</option><option value="rating">Үнэлгээ өндөр</option><option value="title">Нэрээр</option></select></label></div></section><div className="catalog-summary"><span>● БҮТЭЭЛ: <b>{filtered.length}</b></span><i>/</i><span>НИЙТ АНГИ, БҮЛЭГ: <b>{chapters}</b></span></div>{filtered.length?<div className="catalog-grid">{filtered.map(item=><CatalogCard item={item} key={item.id}/>)}</div>:<div className="collection-empty"><span>⌕</span><h2>Бүтээл олдсонгүй</h2><p>Шүүлтүүрээ өөрчлөөд дахин оролдоно уу.</p></div>}</main></Chrome>;
}
