"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, ChevronDown, Search } from "lucide-react";
import { Chrome } from "../components/Chrome";
import type { CatalogItem } from "../data/catalog";

function CatalogCard({item}:{item:CatalogItem}){const count=item.type==="anime"?`${item.episodes??0} АНГИ`:`${item.chapters??0} БҮЛЭГ`;return <a className="catalog-card" href={`/title/${item.id}`}><div className="catalog-poster"><img src={item.image} alt={item.title}/><b>{item.type==="anime"?"АНИМЭ":"МАНГА"}</b><span><small>{count}</small><small>★ {item.rating.toFixed(1)}</small></span></div><div><h2>{item.title}</h2><i>→</i><p>{item.type==="anime"?"АНИМЭ":"МАНХВА / МАНГА"} · {item.status.toUpperCase()}</p></div></a>}
function FilterSelect({label,value,options,onChange}:{label:string;value:string;options:{value:string;label:string}[];onChange:(value:string)=>void}){const selected=options.find(option=>option.value===value)?.label||options[0]?.label;return <label className="catalog-filter"><small>{label}</small><details><summary><span>{selected}</span><ChevronDown size={16}/></summary><div>{options.map(option=><button type="button" className={value===option.value?"active":""} key={option.value} onClick={event=>{onChange(option.value);const details=event.currentTarget.closest("details");if(details)details.open=false}}><span>{option.label}</span>{value===option.value&&<Check size={15}/>}</button>)}</div></details></label>}

export default function CatalogPage(){
  const [items,setItems]=useState<CatalogItem[]>([]);const [query,setQuery]=useState("");const [type,setType]=useState("all");const [genre,setGenre]=useState("all");const [status,setStatus]=useState("all");const [sort,setSort]=useState("newest");
  useEffect(()=>{const params=new URLSearchParams(window.location.search);setType(params.get("type")||"all");fetch("/api/catalog").then(r=>r.json()).then(data=>setItems(data.items||[])).catch(()=>setItems([]))},[]);
  const genres=useMemo(()=>Array.from(new Set(items.flatMap(item=>item.genres))).sort(),[items]);
  const filtered=useMemo(()=>{const needle=query.toLowerCase();const result=items.filter(item=>(!needle||`${item.title} ${item.originalTitle}`.toLowerCase().includes(needle))&&(type==="all"||(type==="manga"?item.type!=="anime":item.type===type))&&(genre==="all"||item.genres.includes(genre))&&(status==="all"||item.status.toLowerCase()===status.toLowerCase()));return result.sort((a,b)=>sort==="rating"?b.rating-a.rating:sort==="title"?a.title.localeCompare(b.title):b.year-a.year)},[items,query,type,genre,status,sort]);
  const chapters=filtered.reduce((sum,item)=>sum+(item.type==="anime"?(item.episodes||0):(item.chapters||0)),0);
  return <Chrome searchValue={query} onSearchChange={setQuery}><main className="catalog-page"><section className="catalog-filter-panel"><label className="catalog-search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Хайх..."/></label><div className="catalog-filters"><FilterSelect label="АНГИЛАЛ" value={type} onChange={setType} options={[{value:"all",label:"Бүгд"},{value:"anime",label:"Анимэ"},{value:"manga",label:"Манга"}]}/><FilterSelect label="ТӨРӨЛ" value={genre} onChange={setGenre} options={[{value:"all",label:"Бүгд"},...genres.map(value=>({value,label:value}))]}/><FilterSelect label="ТӨЛӨВ" value={status} onChange={setStatus} options={[{value:"all",label:"Бүгд"},{value:"On-Going",label:"Ongoing"},{value:"Completed",label:"Completed"},{value:"Hiatus",label:"Hiatus"}]}/><FilterSelect label="ЭРЭМБЭ" value={sort} onChange={setSort} options={[{value:"newest",label:"Шинээр нэмэгдсэн"},{value:"rating",label:"Үнэлгээ өндөр"},{value:"title",label:"Нэрээр"}]}/></div></section><div className="catalog-summary"><span>● БҮТЭЭЛ: <b>{filtered.length}</b></span><i>/</i><span>НИЙТ АНГИ, БҮЛЭГ: <b>{chapters}</b></span></div>{filtered.length?<div className="catalog-grid">{filtered.map(item=><CatalogCard item={item} key={item.id}/>)}</div>:<div className="collection-empty"><span>⌕</span><h2>Бүтээл олдсонгүй</h2><p>Шүүлтүүрээ өөрчлөөд дахин оролдоно уу.</p></div>}</main></Chrome>;
}
