"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, ChevronDown, Funnel, Search } from "lucide-react";
import { Chrome } from "../components/Chrome";
import type { CatalogItem } from "../data/catalog";

function CatalogCard({item}:{item:CatalogItem}){const count=item.type==="anime"?`${item.episodes??0} АНГИ`:`${item.chapters??0} БҮЛЭГ`;return <a className="catalog-card" href={`/title/${item.id}`}><div className="catalog-poster"><img src={item.image} alt={item.title}/><small className="catalog-count">{count}</small></div><div><h2>{item.title}</h2></div></a>}
function FilterSelect({id,label,value,options,open,onToggle,onChange}:{id:string;label:string;value:string;options:{value:string;label:string}[];open:boolean;onToggle:(id:string|null)=>void;onChange:(value:string)=>void}){const selected=options.find(option=>option.value===value)?.label||options[0]?.label;return <div className="catalog-filter"><small>{label}</small><div className={`catalog-filter-menu ${open?"open":""}`}><button className="catalog-filter-trigger" type="button" aria-expanded={open} onClick={()=>onToggle(open?null:id)}><span>{selected}</span><ChevronDown size={16}/></button>{open&&<div className="catalog-filter-options">{options.map(option=><button type="button" className={value===option.value?"active":""} key={option.value} onClick={()=>{onChange(option.value);onToggle(null)}}><span>{option.label}</span>{value===option.value&&<Check size={15}/>}</button>)}</div>}</div></div>}

export default function CatalogPage(){
  const [items,setItems]=useState<CatalogItem[]>([]);const [query,setQuery]=useState("");const [type,setType]=useState("all");const [genre,setGenre]=useState("all");const [status,setStatus]=useState("all");const [sort,setSort]=useState("newest");const [openFilter,setOpenFilter]=useState<string|null>(null);const [filtersOpen,setFiltersOpen]=useState(false);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);setType(params.get("type")||"all");fetch("/api/catalog").then(r=>r.json()).then(data=>setItems(data.items||[])).catch(()=>setItems([]))},[]);
  const genres=useMemo(()=>Array.from(new Set(items.flatMap(item=>item.genres))).sort(),[items]);
  const filtered=useMemo(()=>{const needle=query.toLowerCase();const result=items.filter(item=>(!needle||`${item.title} ${item.originalTitle}`.toLowerCase().includes(needle))&&(type==="all"||(type==="manga"?item.type!=="anime":item.type===type))&&(genre==="all"||item.genres.includes(genre))&&(status==="all"||item.status.toLowerCase()===status.toLowerCase()));return result.sort((a,b)=>sort==="rating"?b.rating-a.rating:sort==="title"?a.title.localeCompare(b.title):b.year-a.year)},[items,query,type,genre,status,sort]);
  return <Chrome searchValue={query} onSearchChange={setQuery}><main className="catalog-page" onClick={event=>{if(event.target===event.currentTarget)setOpenFilter(null)}}><section className="catalog-filter-panel"><div className="catalog-search-row"><label className="catalog-search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`${type==="anime"?"Анимэ":type==="manga"?"Манга":"Бүтээл"} хайх...`}/></label><button className={`mobile-filter-toggle ${filtersOpen?"active":""}`} type="button" onClick={()=>setFiltersOpen(value=>!value)} aria-label="Шүүлтүүр"><Funnel size={20}/></button></div><div className={`catalog-filters ${filtersOpen?"mobile-open":""}`}><FilterSelect id="type" label="АНГИЛАЛ" value={type} open={openFilter==="type"} onToggle={setOpenFilter} onChange={setType} options={[{value:"all",label:"Бүгд"},{value:"anime",label:"Анимэ"},{value:"manga",label:"Манга"}]}/><FilterSelect id="genre" label="ТӨРӨЛ" value={genre} open={openFilter==="genre"} onToggle={setOpenFilter} onChange={setGenre} options={[{value:"all",label:"Бүгд"},...genres.map(value=>({value,label:value}))]}/><FilterSelect id="status" label="ТӨЛӨВ" value={status} open={openFilter==="status"} onToggle={setOpenFilter} onChange={setStatus} options={[{value:"all",label:"Бүгд"},{value:"On-Going",label:"Ongoing"},{value:"Completed",label:"Completed"},{value:"Hiatus",label:"Hiatus"}]}/><FilterSelect id="sort" label="ЭРЭМБЭ" value={sort} open={openFilter==="sort"} onToggle={setOpenFilter} onChange={setSort} options={[{value:"newest",label:"Шинээр нэмэгдсэн"},{value:"rating",label:"Үнэлгээ өндөр"},{value:"title",label:"Нэрээр"}]}/></div></section><div className="catalog-summary"><span>● БҮТЭЭЛ: <b>{filtered.length}</b></span><i>/</i><span>НИЙТ АНГИ, БҮЛЭГ: <b>{chapters}</b></span></div>{filtered.length?<div className="catalog-grid">{filtered.map(item=><CatalogCard item={item} key={item.id}/>)}</div>:<div className="collection-empty"><span>⌕</span><h2>Бүтээл олдсонгүй</h2><p>Шүүлтүүрээ өөрчлөөд дахин оролдоно уу.</p></div>}</main></Chrome>;
}
